name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug
    - name: Upload APK to Artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: '**/*.apk'
    - name: Publish target APK to Github Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: '**/*.apk'
